spring.application.name=ai-backend

spring.datasource.url=jdbc:postgresql://dpg-d6fi6fggjchc73a5h7lg-a.singapore-postgres.render.com:5432/ai_chat_db_9cah
spring.datasource.username=ai_chat_db_9cah_user
spring.datasource.password=y8SHmsVwhyM31fFvEVnQPLOZXyRjAR56
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
